name: Build Comic App
on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Create credentials file
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        run: |
          echo "$CREDENTIAL_FILE_CONTENT" > credentials.json
          ls -la
          cat credentials.json

      - name: List files in build context
        run: ls -la  
      
      - name: Login to docker hub
        run: |
          docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build docker image
        run: docker build -t ${{ vars.DOCKER_USER }}/node_comic_app .

      - name: Publish image to docker hub
        run: docker push ${{ vars.DOCKER_USER }}/node_comic_app:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Delete old container
        run: docker rm -f node_comic_app_container || true
      
      - name: Pull image from docker hub
        run: docker pull ${{ vars.DOCKER_USER }}/node_comic_app:latest


      - name: Run docker container
        run: docker run -d -p 3000:3000 --name node_comic_app_container ${{ vars.DOCKER_USER }}/node_comic_app
